set -g prefix C-a
unbind C-b
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -g base-index 1
set -g pane-base-index 1
set -g status on
set -g status-position bottom
set -g status-style "bg=#21252b,fg=#abb2bf"
set -g status-left "#[bg=#61afef,fg=#282c34,bold]  #S #[bg=#21252b,fg=#61afef]"
set -g status-left-length 30
set -g status-right "#[fg=#949cab,bg=#21252b]  studio #[fg=#3e4451]│#[fg=#949cab] 09:41 "
set -g status-right-length 40
setw -g window-status-format "#[fg=#5c6370] #I #[fg=#949cab]#W "
setw -g window-status-current-format "#[fg=#282c34,bg=#98c379,bold] #I #[fg=#d7dae0,bg=#2c313c] #W #[fg=#2c313c,bg=#21252b]"
setw -g window-status-separator ""
set -g pane-border-style "fg=#3e4451"
set -g pane-active-border-style "fg=#61afef"
set -g mouse on
